apiVersion: v1
kind: Namespace
metadata:
  name: hello-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-k8s
  name: deployment-hello-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: hello-k8s
  name: service-hello-k8s
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: hello-k8s
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: hello-k8s
  name: ingress-hello-k8s
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-hello-k8s
              servicePort: 80
